# Generated by Django 3.0.6 on 2020-05-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='bodytex',
            new_name='bodytext',
        ),
    ]
